name: develop CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: get Github Repository
        uses: actions/checkout@v4

      - name: install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create resources directory if it does not exist
        run: mkdir -p ./src/main/resources

      - name: create application.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: test and build
        run: ./gradlew clean build

      - name: change build file name
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: send build file to EC2 with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/reconnect_server/tobe

      - name: connect to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            # 1. 'current' 디렉토리 제거
            sudo rm -rf /home/reconnect_server/current || true

            # 2. 필요한 디렉토리 생성
            sudo mkdir -p /home/reconnect_server/{tobe,current,logs}

            # 3. JAR 파일 이동
            sudo mv /home/reconnect_server/tobe/project.jar /home/reconnect_server/current/project.jar

            # 4. 포트 8080 실행 중인 프로세스 종료
            pid=$(lsof -t -i :8080)
            if [ -n "$pid" ]; then
              echo "Killing process $pid..."
              sudo kill $pid
            else
              echo "No process found on port 9475."
            fi

            # 5. 서버 시작
            cd /home/reconnect_server/current
            nohup java -jar project.jar --spring.profiles.active=local > /home/reconnect_server/logs/server.log 2>&1 &
            if [ $? -ne 0 ]; then
              echo "Failed to start server process"
              exit 1
            fi

            # 6. 'tobe' 디렉토리 제거
            sudo rm -rf /home/reconnect_server/tobe || true
